[package]
name = "shr-chip-8-emu"
version = "0.1.0"
authors = ["Ilia Eliseev <sharzon.soft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "^0.24.0"
pixels = "^0.2.0"